#!/bin/sh
killall Xvfb x11mac eventmap

Xvfb \
	-retro \
	-ac \
	-screen 0 512x384x8 \
	-fbdir /tmp/ \
	+extension XTEST \
	&

sleep 5

export DISPLAY=:0

xterm -geometry +10+10 &
xeyes -geometry -0-0 &

./x11mac /tmp/Xvfb_screen0 &
./eventmap /dev/input/event* &
